export const SAJU_ADAPTER_CAPABILITIES = {
  manifestVersion: 1,
  adapterVersion: '0.1.0',
  profile: { version: 'korean-saju-v1', status: 'candidate' },
  supportedCalendars: ['solar'],
  supportedTimeZones: ['Asia/Seoul'],
  supportedCivilDateRange: { minimum: '1989-01-01', maximum: '2024-12-31' },
  timezoneStrategy: { value: 'fixed-utc-plus-09-civil-time', dataVersion: 'fixed-kst-utc-plus-09-1989-2024-v1', status: 'bounded-candidate' },
  completeCalculationRequires: { timePrecision: 'exact', ambiguity: 'unambiguous' },
  yearBoundary: { value: 'precise-ipchun-instant', source: 'manseryeok-embedded-table', precision: 'minute', status: 'candidate', productionValidated: false },
  monthBoundary: { value: 'twelve-jie-solar-term-instants', source: 'manseryeok-embedded-table', precision: 'minute', status: 'candidate', productionValidated: false },
  dayBoundary: { value: 'midnight', status: 'candidate', productionValidated: false },
  hourBranchConvention: { value: 'civil-two-hour-intervals-from-23:00', status: 'candidate', productionValidated: false },
  trueSolarTime: { enabled: false, status: 'candidate', productionValidated: false },
  unknownTime: { fabricatedDefault: false, result: 'partial-with-no-pillars' },
  approximateTime: { status: 'unsupported', owner: 'Issue #12' },
  disputedTime: { status: 'unsupported', owner: 'Issue #12' },
  derivedFeatures: { status: 'not-applicable', owner: 'Issue #13' },
  historicalTimeZonePolicy: { status: 'unsupported', owner: 'Issue #9' },
  hiddenStems: { status: 'out-of-scope' },
  daewoon: { status: 'out-of-scope' },
  genderDirectedCalculations: { status: 'out-of-scope' },
  productionEligible: false,
  pendingEvidence: [
    'Historical/future Asia/Seoul and non-Korean timezone normalization in Issue #9',
    'Korean methodology/expert review',
    'Issue #14 >=200 reference-backed golden corpus',
  ],
} as const;
